version: '3.8'

volumes:
  tron_data:
  tron_static:
  tron_media:

services:
  db:
    image: postgres:13-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - tron_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: ./src
    env_file: .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
    volumes:
      - ./src/app:/app/app
  gateway:
    build: ./nginx
    env_file: .env
    depends_on:
      - app
    volumes:
      - tron_media:/app/media
      - tron_static:/staticfiles
    ports:
      - 80:80
