"""empty message

Revision ID: 3b29c9830e92
Revises: 
Create Date: 2025-03-28 14:05:50.522092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b29c9830e92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walletinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True, comment='Дата обновления'),
    sa.Column('wallet_id', sa.String(length=34), nullable=False, comment='Уникальный идентификатор кошелька в сети Tron'),
    sa.Column('trx_balance', sa.DECIMAL(precision=20, scale=6), nullable=True, comment='Текущий баланс TRX с точностью до 6 знаков'),
    sa.Column('energy_limit', sa.Integer(), nullable=True, comment='Лимит энергии'),
    sa.Column('free_net_limit', sa.Integer(), nullable=True, comment='Бесплатный лимит BP'),
    sa.Column('net_limit', sa.Integer(), nullable=True, comment='Общий лимит BP'),
    sa.Column('free_net_used', sa.Integer(), nullable=True, comment='Использовано бесплатных BP'),
    sa.Column('net_used', sa.Integer(), nullable=True, comment='Всего использовано BP'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walletinfo_id'), 'walletinfo', ['id'], unique=False)
    op.create_index(op.f('ix_walletinfo_wallet_id'), 'walletinfo', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_walletinfo_wallet_id'), table_name='walletinfo')
    op.drop_index(op.f('ix_walletinfo_id'), table_name='walletinfo')
    op.drop_table('walletinfo')
    # ### end Alembic commands ###
